openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: Documentazione API con Swagger in YAML
servers:
  - url: http://localhost:4000

paths:
  /api/auth/login:
    post:
      summary: Effettua il login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login effettuato con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Credenziali non valide

  /api/auth/register:
    post:
      summary: Registra un nuovo utente
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: Utente registrato con successo
        "400":
          description: Richiesta non valida
